[tovplay_servers]
production ansible_host=193.181.213.220 ansible_user=admin ansible_password=<REDACTED_TOVTECH_ANSIBLE_PASSWORD> ansible_become_password=<REDACTED_TOVTECH_ANSIBLE_PASSWORD>
staging ansible_host=92.113.144.59 ansible_user=admin ansible_password=<REDACTED_TOVTECH_ANSIBLE_PASSWORD> ansible_become_password=<REDACTED_TOVTECH_ANSIBLE_PASSWORD>

[tovplay_servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
