function ccsizes {
    Write-Host '=== PURGING SAFE-TO-WIPE FOLDERS ===' -ForegroundColor Red
    $startTime = Get-Date
    $safePaths = @(
        # ===== ORIGINAL PATHS =====
        "C:\Windows\Temp",
        "C:\Windows\SoftwareDistribution\Download",
        "C:\Windows\SoftwareDistribution\DataStore",
        "C:\Windows\Prefetch",
        "C:\Windows\Logs",
        "C:\Windows\Panther",
        "C:\Windows\System32\LogFiles",
        "C:\Windows\Minidump",
        "C:\Windows\LiveKernelReports",
        "C:\Windows\WinSxS\Temp",
        "C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp",
        "C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp",
        "C:\PerfLogs",
        "C:\`$Recycle.Bin",
        "C:\ProgramData\Microsoft\Windows\WER",
        "C:\ProgramData\Microsoft\Search",
        "C:\ProgramData\Microsoft\Network",
        "C:\ProgramData\Microsoft\Diagnosis",
        "C:\ProgramData\Microsoft\Windows Defender\Scans",
        "C:\ProgramData\USOShared\Logs",
        "C:\ProgramData\Package Cache",
        "C:\ProgramData\chocolatey\logs",
        "C:\ProgramData\NVIDIA Corporation\Downloader",
        "C:\ProgramData\DockerDesktop\log",
        "C:\Users\micha\AppData\Local\Temp",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\INetCache",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\WebCache",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\Explorer",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\Caches",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\WER",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\Temporary Internet Files",
        "C:\Users\micha\AppData\Local\Microsoft\Terminal Server Client\Cache",
        "C:\Users\micha\AppData\Local\CrashDumps",
        "C:\Users\micha\AppData\Local\D3DSCache",
        "C:\Users\micha\AppData\Local\ConnectedDevicesPlatform",
        "C:\Users\micha\AppData\Local\Comms\UnistoreDB",
        "C:\Users\micha\AppData\Local\DBG",
        "C:\Users\micha\AppData\Local\FontCache",
        "C:\Users\micha\AppData\Local\IconCache.db",
        "C:\Users\micha\AppData\Local\SquirrelTemp",
        "C:\Users\micha\.nuget\packages",
        "C:\Users\micha\.gradle\caches",
        "C:\Users\micha\.m2\repository",
        "C:\Users\micha\.cargo\registry",
        "C:\Users\micha\.rustup\downloads",
        "C:\Users\micha\.cache",
        "C:\Users\micha\AppData\Local\pip\cache",
        "C:\Users\micha\AppData\Local\npm-cache",
        "C:\Users\micha\AppData\Roaming\npm-cache",
        "C:\Users\micha\AppData\Local\yarn\cache",
        "C:\Users\micha\AppData\Local\pnpm\cache",
        "C:\Users\micha\AppData\Local\NuGet\Cache",
        "C:\Users\micha\AppData\Local\Composer\cache",
        "C:\Users\micha\AppData\Local\go-build",
        "C:\Users\micha\AppData\Local\deno\deps",
        "C:\Users\micha\AppData\Local\node-gyp",
        "C:\Users\micha\AppData\Local\vcpkg",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Default\Cache",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Default\Code Cache",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\ShaderCache",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\GPUCache",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\Default\Cache",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\Default\Code Cache",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\ShaderCache",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\GPUCache",
        "C:\Users\micha\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Cache",
        "C:\Users\micha\AppData\Local\Mozilla\Firefox\Profiles",
        "C:\Users\micha\AppData\Local\Microsoft\VisualStudio",
        "C:\Users\micha\AppData\Local\JetBrains\Transient",
        "C:\Users\micha\AppData\Local\Cursor\Cache",
        "C:\Users\micha\AppData\Roaming\Code\Cache",
        "C:\Users\micha\AppData\Roaming\Code\CachedData",
        "C:\Users\micha\AppData\Roaming\Code\CachedExtensions",
        "C:\Users\micha\AppData\Roaming\Code\logs",
        "C:\Users\micha\AppData\Roaming\Code\User\workspaceStorage",
        "C:\Users\micha\AppData\Local\Slack\Cache",
        "C:\Users\micha\AppData\Local\Slack\Code Cache",
        "C:\Users\micha\AppData\Local\Slack\GPUCache",
        "C:\Users\micha\AppData\Local\Discord\Cache",
        "C:\Users\micha\AppData\Local\Discord\Code Cache",
        "C:\Users\micha\AppData\Local\Microsoft\Teams\Cache",
        "C:\Users\micha\AppData\Local\Microsoft\Teams\tmp",
        "C:\Users\micha\AppData\Local\Spotify\Data",
        "C:\Users\micha\AppData\Local\Docker\log",
        "C:\Users\micha\AppData\Local\Docker\wsl\data",
        "C:\Users\micha\AppData\Roaming\Claude\Cache",
        "C:\Users\micha\AppData\Local\electron\Cache",
        "C:\Users\micha\AppData\Local\Postman\logs",
        "C:\Users\micha\AppData\Local\GitHubDesktop\logs",
        "C:\Users\micha\AppData\Local\Steam\htmlcache",
        "C:\Users\micha\AppData\Roaming\Zoom\logs",
        "C:\Users\micha\AppData\Roaming\Microsoft\Windows\Recent",
        "C:\Windows\Installer\`$PatchCache`$",
        "C:\Windows\Debug",
        "C:\Windows\CbsTemp",
        "C:\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache",
        "C:\Windows\SoftwareDistribution\PostRebootEventCache.V2",
        "C:\Windows\SystemTemp",
        "C:\`$SysReset",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Crashpad",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Default\blob_storage",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Default\Service Worker",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Default\Session Storage",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Default\Local Storage",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Default\IndexedDB",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\Crashpad",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\Default\blob_storage",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\Default\Service Worker",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\Default\Session Storage",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\Default\Local Storage",
        "C:\Users\micha\AppData\Local\Google\Chrome for Testing",
        "C:\Users\micha\AppData\Local\ms-playwright",
        "C:\Users\micha\AppData\Local\AMD\DxCache",
        "C:\Users\micha\AppData\Local\AMD\VkCache",
        "C:\Users\micha\AppData\LocalLow\AMD\DxcCache",
        "C:\Users\micha\AppData\Local\NVIDIA\GLCache",
        "C:\Users\micha\AppData\Local\NVIDIA\DXCache",
        "C:\Users\micha\AppData\Local\AMD Ryzen Master\cache",
        "C:\Users\micha\AppData\Local\AMD\RadeonSoftware\cache",
        "C:\Users\micha\AppData\Local\NVIDIA Corporation\NVIDIA App\CefCache",
        "C:\Users\micha\AppData\Local\NVIDIA Corporation\NVIDIA Overlay\CefCache",
        "C:\Users\micha\AppData\Roaming\Antigravity\Cache",
        "C:\Users\micha\AppData\Roaming\Antigravity\CachedData",
        "C:\Users\micha\AppData\Roaming\Antigravity\Code Cache",
        "C:\Users\micha\AppData\Roaming\Antigravity\GPUCache",
        "C:\Users\micha\AppData\Roaming\Antigravity\logs",
        "C:\Users\micha\AppData\Roaming\Antigravity\Crashpad",
        "C:\Users\micha\AppData\Roaming\AnyDesk\cache",
        "C:\Users\micha\AppData\Roaming\Claude\Code Cache",
        "C:\Users\micha\AppData\Roaming\Claude\GPUCache",
        "C:\Users\micha\AppData\Roaming\Claude\logs",
        "C:\Users\micha\AppData\Roaming\Claude\Crashpad",
        "C:\Users\micha\AppData\Roaming\Claude\blob_storage",
        "C:\Users\micha\AppData\Roaming\Docker Desktop\Cache",
        "C:\Users\micha\AppData\Roaming\Docker Desktop\Code Cache",
        "C:\Users\micha\AppData\Roaming\Docker Desktop\GPUCache",
        "C:\Users\micha\AppData\Roaming\GitHub Desktop\Cache",
        "C:\Users\micha\AppData\Roaming\GitHub Desktop\Code Cache",
        "C:\Users\micha\AppData\Roaming\GitHub Desktop\GPUCache",
        "C:\Users\micha\AppData\Roaming\GitHub Desktop\logs",
        "C:\Users\micha\AppData\Roaming\Wand\Code Cache",
        "C:\Users\micha\AppData\Roaming\WeMod\Cache",
        "C:\Users\micha\AppData\Roaming\WeMod\Code Cache",
        "C:\Users\micha\AppData\Roaming\WeMod\GPUCache",
        "C:\Users\micha\AppData\Roaming\WeMod\games\crash",
        "C:\Users\micha\AppData\Roaming\WeMod\games\logs",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\ActionCenterCache",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\AppCache",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\Notifications",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\History",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\Burn",
        "C:\Users\micha\AppData\Local\Microsoft\Media Player",
        "C:\Users\micha\AppData\Local\Microsoft\TokenBroker\Cache",
        "C:\Users\micha\AppData\Local\Microsoft\Internet Explorer\CacheStorage",
        "C:\Users\micha\AppData\Local\Microsoft\Olk\logs",
        "C:\Users\micha\AppData\Local\Microsoft\Olk\EBWebView\Crashpad",
        "C:\Users\micha\AppData\Local\Microsoft\Olk\EBWebView\ShaderCache",
        "C:\ProgramData\AnyDesk\cache",
        "C:\ProgramData\Corsair\CorsairDeviceControlService\logs",
        "C:\ProgramData\Microsoft\EdgeUpdate\Log",
        "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Cache",
        "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Temp",
        "C:\ProgramData\Microsoft\Windows Security Health\Logs",
        "C:\ProgramData\Microsoft\Windows\Caches",
        "C:\ProgramData\NVIDIA",
        "C:\ProgramData\NVIDIA Corporation\NvTelemetry",
        "C:\Users\micha\.bun\install\cache",
        "C:\Users\micha\AppData\Local\uv\cache",
        "C:\Users\micha\AppData\Local\claude-cli-nodejs\Cache",
        "C:\Users\micha\AppData\Local\launcher\cache",
        "C:\Users\micha\AppData\Local\Setup\cache",
        "C:\Users\micha\AppData\Local\qBittorrent\cache",
        "C:\Users\micha\AppData\Local\qBittorrent\logs",
        "C:\Users\micha\.docker\buildx",
        "C:\Users\micha\.claude\projects",
        "C:\Users\micha\AppData\Local\Temp\claude",
        "C:\Users\micha\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine",
        "C:\Users\micha\.local\share\opencode\log",
        "C:\Users\micha\AppData\Local\Claude\Logs",
        "C:\Users\micha\AppData\Local\DeliverUsMars\Saved\Logs",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.WidgetsPlatformRuntime_8wekyb3d8bbwe\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.Windows.ShellExperienceHost_cw5n1h2txyewy\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.WindowsAppRuntime.1.7_8wekyb3d8bbwe\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.WindowsNotepad_8wekyb3d8bbwe\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\Microsoft.Winget.Source_8wekyb3d8bbwe\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\MicrosoftWindows.Client.CoreAI_cw5n1h2txyewy\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\MicrosoftWindows.Client.Core_cw5n1h2txyewy\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\MicrosoftWindows.CrossDevice_cw5n1h2txyewy\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\windows_ie_ac_001\AC\Temp",
        "C:\Users\micha\AppData\Local\Packages\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\LocalState\EBWebView\Crashpad",
        "C:\Users\micha\AppData\Local\Packages\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\LocalState\EBWebView\ShaderCache",
        "C:\Users\micha\AppData\Local\Packages\MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy\LocalState\EBWebView\Crashpad",
        "C:\Users\micha\AppData\Local\Packages\MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy\LocalState\EBWebView\ShaderCache",
        "C:\Users\micha\AppData\Roaming\Code\Crashpad",
        "C:\Users\micha\AppData\Roaming\Code\GPUCache",
        "C:\Users\micha\AppData\Local\Cursor\CachedData",
        "C:\Users\micha\AppData\Local\Cursor\GPUCache",
        "C:\Users\micha\AppData\Local\Cursor\Crashpad",
        # ===== NEW PATHS (v5) =====
        "C:\Program Files (x86)\Microsoft\temp",
        "C:\Program Files (x86)\Mozilla Maintenance Service\logs",
        "C:\Program Files\Git\tmp",
        "C:\ProgramData\PreBootRepair\logs",
        "C:\ProgramData\Microsoft\Diagnosis\ETLLogs",
        "C:\ProgramData\Microsoft\Windows Defender\Definition Updates",
        "C:\ProgramData\Microsoft\Windows Defender\Support",
        "C:\Windows\appcompat\backup",
        "C:\Windows\assembly\temp",
        "C:\Windows\assembly\tmp",
        "C:\Windows\rescache",
        "C:\Windows\security\logs",
        "C:\Windows\Setup\Scripts",
        "C:\Windows\Setup\State",
        "C:\Windows\servicing\Packages",
        "C:\Windows\Downloaded Program Files",
        "C:\Windows\Offline Web Pages",
        "C:\Windows\System32\sru",
        "C:\Windows\System32\Tasks_Migrated",
        "C:\Windows\System32\winevt\Logs",
        "C:\Windows\System32\WDI\LogFiles",
        "C:\Windows\System32\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache",
        "C:\Windows\System32\DriverStore\Temp",
        "C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache",
        "C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\Cache",
        "C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\Logs",
        "C:\Users\micha\AppData\Roaming\AnyDesk\Cache",
        "C:\Users\micha\AppData\Roaming\ascendara\blob_storage",
        "C:\Users\micha\AppData\Roaming\ascendara\Cache",
        "C:\Users\micha\AppData\Roaming\ascendara\Code Cache",
        "C:\Users\micha\AppData\Roaming\ascendara\GPUCache",
        "C:\Users\micha\AppData\Roaming\gametrainer-pro\blob_storage",
        "C:\Users\micha\AppData\Roaming\gametrainer-pro\Cache",
        "C:\Users\micha\AppData\Roaming\gametrainer-pro\Code Cache",
        "C:\Users\micha\AppData\Roaming\gametrainer-pro\GPUCache",
        "C:\Users\micha\AppData\Roaming\hydralauncher\blob_storage",
        "C:\Users\micha\AppData\Roaming\hydralauncher\Cache",
        "C:\Users\micha\AppData\Roaming\hydralauncher\Code Cache",
        "C:\Users\micha\AppData\Roaming\hydralauncher\GPUCache",
        "C:\Users\micha\AppData\Roaming\hydralauncher\logs",
        "C:\Users\micha\AppData\Roaming\Wand\blob_storage",
        "C:\Users\micha\AppData\Roaming\Wand\Cache",
        "C:\Users\micha\AppData\Roaming\Wand\GPUCache",
        "C:\Users\micha\AppData\Local\Microsoft\OneDrive\setup\logs",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\IECompatCache",
        "C:\Users\micha\AppData\Local\Microsoft\Windows\IECompatUaCache",
        "C:\Users\micha\AppData\Local\Google\Chrome\User Data\Default\Storage\ext",
        "C:\Users\micha\AppData\Local\Microsoft\Edge\User Data\Default\Storage\ext",
        "C:\Users\micha\AppData\Local\winutil\logs"
    )
    
    $totalBefore = 0
    foreach ($p in $safePaths) {
        if (Test-Path $p -EA 0) {
            $s = (Get-ChildItem $p -Recurse -Force -EA 0 | Measure-Object Length -Sum -EA 0).Sum
            if ($s) { $totalBefore += $s }
        }
    }
    
    Write-Host ('Total before: {0:N2} GB' -f ($totalBefore/1GB)) -ForegroundColor Yellow
    
    $purged = 0
    foreach ($path in $safePaths) {
        if (Test-Path $path -EA 0) {
            $sizeBefore = (Get-ChildItem $path -Recurse -Force -EA 0 | Measure-Object Length -Sum -EA 0).Sum
            if ($sizeBefore -gt 1MB) {
                Write-Host 'Purging: ' $path -ForegroundColor Cyan -NoNewline
                Get-ChildItem $path -Force -EA 0 | Remove-Item -Recurse -Force -EA SilentlyContinue
                $sizeAfter = (Get-ChildItem $path -Recurse -Force -EA 0 | Measure-Object Length -Sum -EA 0).Sum
                if (-not $sizeAfter) { $sizeAfter = 0 }
                $freed = $sizeBefore - $sizeAfter
                $purged += $freed
                Write-Host (' - Freed {0:N0} MB' -f ($freed/1MB)) -ForegroundColor Green
            }
        }
    }
    
    Write-Host 'Emptying Recycle Bin...' -ForegroundColor Cyan
    Clear-RecycleBin -Force -EA SilentlyContinue
    Write-Host ' - Done' -ForegroundColor Green
    
    $elapsed = (Get-Date) - $startTime
    Write-Host ''
    Write-Host '=== PURGE COMPLETE ===' -ForegroundColor Green
    Write-Host ('Total purged: {0:N2} GB' -f ($purged/1GB)) -ForegroundColor Green
    Write-Host ('Time elapsed: {0:N1} seconds' -f $elapsed.TotalSeconds) -ForegroundColor Cyan
    if ($totalBefore -gt 0) {
        $pct = ($purged/$totalBefore)*100
        Write-Host ('Purge rate: {0:N1}%' -f $pct) -ForegroundColor $(if($pct -ge 70){'Green'}else{'Yellow'})
    }
}
