"""Added CASCADE delete to missing foreign keys

Revision ID: 20aa228df203
Revises: 
Create Date: 2025-11-12 12:16:34.089341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20aa228df203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ScheduledSession', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('game_site_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('UserNotifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text('\'"General"\'::character varying'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserNotifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text('\'"General"\'::character varying'))

    with op.batch_alter_table('ScheduledSession', schema=None) as batch_op:
        batch_op.alter_column('game_site_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
