"""Update User hashed_password length to 100

Revision ID: 6a0a420e2650
Revises: b6ee4a399873
Create Date: 2025-11-13 12:23:07.483160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a0a420e2650'
down_revision = 'b6ee4a399873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('GameRequest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('GameRequest_recipient_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('GameRequest_sender_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['sender_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['recipient_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ScheduledSession', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ScheduledSession_organizer_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ScheduledSession_session_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ScheduledSession_second_player_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['second_player_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['organizer_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'GameRequest', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('UserAvailability', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('UserAvailability_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('UserGamePreference', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('UserGamePreference_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('UserProfile', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_constraint(batch_op.f('UserProfile_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('UserSession', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('UserSession_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserSession', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserSession_user_id_fkey'), 'User', ['user_id'], ['id'])

    with op.batch_alter_table('UserProfile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserProfile_user_id_fkey'), 'User', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('UserGamePreference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserGamePreference_user_id_fkey'), 'User', ['user_id'], ['id'])

    with op.batch_alter_table('UserAvailability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserAvailability_user_id_fkey'), 'User', ['user_id'], ['id'])

    with op.batch_alter_table('ScheduledSession', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ScheduledSession_second_player_id_fkey'), 'User', ['second_player_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ScheduledSession_session_id_fkey'), 'GameRequest', ['session_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ScheduledSession_organizer_user_id_fkey'), 'User', ['organizer_user_id'], ['id'])

    with op.batch_alter_table('GameRequest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('GameRequest_sender_user_id_fkey'), 'User', ['sender_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('GameRequest_recipient_user_id_fkey'), 'User', ['recipient_user_id'], ['id'])

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('password_reset_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_tokens_token_key'))
    )
    # ### end Alembic commands ###
