"""Added CASCADE delete to missing foreign keys

Revision ID: b6ee4a399873
Revises: 20aa228df203
Create Date: 2025-11-12 12:46:15.370465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ee4a399873'
down_revision = '20aa228df203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GameRequest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('GameRequest_sender_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('GameRequest_recipient_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['recipient_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['sender_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ScheduledSession', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ScheduledSession_organizer_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ScheduledSession_second_player_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ScheduledSession_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['organizer_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'GameRequest', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['second_player_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('UserAvailability', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('UserAvailability_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('UserGamePreference', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('UserGamePreference_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('UserProfile', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_constraint(batch_op.f('UserProfile_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('UserSession', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('UserSession_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserSession', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserSession_user_id_fkey'), 'User', ['user_id'], ['id'])

    with op.batch_alter_table('UserProfile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserProfile_user_id_fkey'), 'User', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('UserGamePreference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserGamePreference_user_id_fkey'), 'User', ['user_id'], ['id'])

    with op.batch_alter_table('UserAvailability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserAvailability_user_id_fkey'), 'User', ['user_id'], ['id'])

    with op.batch_alter_table('ScheduledSession', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ScheduledSession_session_id_fkey'), 'GameRequest', ['session_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ScheduledSession_second_player_id_fkey'), 'User', ['second_player_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ScheduledSession_organizer_user_id_fkey'), 'User', ['organizer_user_id'], ['id'])

    with op.batch_alter_table('GameRequest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('GameRequest_recipient_user_id_fkey'), 'User', ['recipient_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('GameRequest_sender_user_id_fkey'), 'User', ['sender_user_id'], ['id'])

    # ### end Alembic commands ###
