export const settingsSearchData = [
  {
    id: "local-index",
    title: "Local Game Index",
    description: "Manage your local game index and refresh settings",
    keywords: [
      "local",
      "game",
      "index",
      "refresh",
      "scan",
      "database",
      "library",
      "rescan",
    ],
    section: "General",
    navigate: navigate => {
      navigate("/localrefresh");
    },
  },
  {
    id: "index-reminder",
    title: "Index Refresh Reminder",
    description: "Set how often to be reminded to refresh your local index",
    keywords: [
      "index",
      "reminder",
      "refresh",
      "notification",
      "alert",
      "days",
      "schedule",
      "local index",
      "remind",
    ],
    section: "General",
    scrollTo: "index-reminder",
  },
  {
    id: "theme",
    title: "Theme",
    description: "Change the appearance theme of Ascendara",
    keywords: [
      "theme",
      "appearance",
      "color",
      "dark",
      "light",
      "custom",
      "style",
      "look",
    ],
    section: "Appearance",
    scrollTo: "theme",
  },
  {
    id: "custom-colors",
    title: "Custom Colors",
    description: "Create your own custom theme",
    keywords: [
      "custom",
      "colors",
      "theme",
      "personalize",
      "palette",
      "customize",
      "color scheme",
    ],
    section: "Appearance",
    scrollTo: "custom-colors",
  },
  {
    id: "smooth-transitions",
    title: "Smooth Transitions",
    description: "Enable smooth page transitions",
    keywords: [
      "smooth",
      "transitions",
      "animations",
      "effects",
      "motion",
      "page transitions",
    ],
    section: "Appearance",
    scrollTo: "smooth-transitions",
  },
  {
    id: "side-scrollbar",
    title: "Side Scrollbar",
    description: "Show scrollbar on the side of pages",
    keywords: ["side", "scrollbar", "scroll", "bar", "sidebar", "show scrollbar"],
    section: "Appearance",
    scrollTo: "side-scrollbar",
  },
  {
    id: "home-search",
    title: "Home Search",
    description: "Show search bar on home page",
    keywords: ["home", "search", "bar", "homepage", "search bar", "home page"],
    section: "Appearance",
    scrollTo: "home-search",
  },
  {
    id: "default-landing-page",
    title: "Default Landing Page",
    description: "Set which page opens when Ascendara starts",
    keywords: [
      "default",
      "landing",
      "page",
      "startup",
      "home",
      "start page",
      "initial page",
      "open on start",
    ],
    section: "Application",
    scrollTo: "default-landing-page",
  },
  {
    id: "auto-update",
    title: "Ascendara Updates / Automatic Updates",
    description: "Automatically download and install Ascendara updates",
    keywords: [
      "ascendara",
      "updates",
      "auto",
      "automatic",
      "update",
      "upgrade",
      "version",
    ],
    section: "Application",
    scrollTo: "auto-update",
  },
  {
    id: "notifications",
    title: "Notifications",
    description: "Enable desktop notifications",
    keywords: [
      "notifications",
      "alerts",
      "toast",
      "notify",
      "desktop notifications",
      "popups",
    ],
    section: "Application",
    scrollTo: "notifications",
  },
  {
    id: "language",
    title: "Language / Language Settings",
    description: "Change the application language",
    keywords: [
      "language",
      "locale",
      "translation",
      "i18n",
      "idioma",
      "langue",
      "sprache",
      "lingua",
      "change language",
    ],
    section: "Application",
    scrollTo: "language",
  },
  {
    id: "download-directory",
    title: "Download Directory / Default Download Location",
    description: "Set where games are downloaded",
    keywords: [
      "download",
      "directory",
      "folder",
      "path",
      "location",
      "default",
      "save location",
      "install location",
    ],
    section: "Downloads",
    scrollTo: "download-directory",
  },
  {
    id: "download-limit",
    title: "Download Speed Limit",
    description: "Limit download speed to prevent network congestion",
    keywords: [
      "download",
      "speed",
      "limit",
      "bandwidth",
      "throttle",
      "cap",
      "restrict",
      "slow down",
    ],
    section: "Downloads",
    scrollTo: "download-limit",
  },
  {
    id: "torrent-downloads",
    title: "Torrent Downloads / Torrenting",
    description: "Enable torrent-based downloads via qBittorrent",
    keywords: [
      "torrent",
      "torrenting",
      "qbittorrent",
      "p2p",
      "bittorrent",
      "peer to peer",
      "enable torrents",
    ],
    section: "Downloads",
    scrollTo: "torrent-downloads",
  },
  {
    id: "post-download-behavior",
    title: "Post-Download Behavior / Behavior After Download",
    description: "Action to perform after downloads complete",
    keywords: [
      "post",
      "download",
      "behavior",
      "after",
      "shutdown",
      "sleep",
      "lock",
      "action",
      "complete",
      "finish",
    ],
    section: "Downloads",
    scrollTo: "post-download-behavior",
  },
  {
    id: "discord-rpc",
    title: "Discord RPC / Discord Rich Presence",
    description: "Show what you're playing on Discord",
    keywords: [
      "discord",
      "rpc",
      "rich",
      "presence",
      "status",
      "activity",
      "show playing",
      "game status",
    ],
    section: "Integrations",
    scrollTo: "discord-rpc",
  },
  {
    id: "ludusavi",
    title: "Game Backup / Ludusavi Integration",
    description: "Backup and restore game saves",
    keywords: [
      "ludusavi",
      "game",
      "backup",
      "saves",
      "restore",
      "save files",
      "game saves",
      "backup saves",
    ],
    section: "Integrations",
    scrollTo: "ludusavi",
  },
  {
    id: "backup-directory",
    title: "Backup Directory / Backup Location",
    description: "Set where game save backups are stored",
    keywords: [
      "backup",
      "directory",
      "location",
      "saves",
      "path",
      "folder",
      "backup location",
      "save location",
    ],
    section: "Integrations",
    scrollTo: "backup-directory",
  },
  {
    id: "exclude-folders",
    title: "Exclude Folders / Protect Directories",
    description:
      "Exclude certain folders from local index scanning and protect from Windows Defender",
    keywords: [
      "exclude",
      "folders",
      "ignore",
      "skip",
      "protect",
      "directories",
      "defender",
      "windows",
      "antivirus",
      "protection",
    ],
    section: "Advanced",
    scrollTo: "exclude-folders",
  },
  {
    id: "quick-launch",
    title: "Quick Launch",
    description: "Keep Ascendara running in background when closed",
    keywords: [
      "quick",
      "launch",
      "background",
      "tray",
      "minimize",
      "close",
      "system tray",
      "keep running",
      "stay open",
    ],
    section: "Application",
    scrollTo: "quick-launch",
  },
  {
    id: "hide-on-game-launch",
    title: "Hide on Game Launch",
    description: "Minimize Ascendara when launching a game",
    keywords: [
      "hide",
      "minimize",
      "game",
      "launch",
      "start",
      "auto hide",
      "automatically hide",
      "when playing",
    ],
    section: "Gaming",
    scrollTo: "hide-on-game-launch",
  },
  {
    id: "mature-content",
    title: "Mature Content",
    description: "Show games with mature/adult content",
    keywords: [
      "mature",
      "content",
      "adult",
      "nsfw",
      "inappropriate",
      "18+",
      "explicit",
      "show mature",
    ],
    section: "Gaming",
    scrollTo: "mature-content",
  },
  {
    id: "auto-create-shortcuts",
    title: "Auto-Create Shortcuts",
    description: "Automatically create desktop shortcuts for installed games",
    keywords: [
      "auto",
      "create",
      "shortcuts",
      "desktop",
      "automatic",
      "automatically",
      "game shortcuts",
      "icons",
    ],
    section: "Gaming",
    scrollTo: "auto-create-shortcuts",
  },
  {
    id: "big-picture-settings",
    title: "Big Picture Mode / Big Picture Settings",
    description: "Configure Big Picture mode settings and controller options",
    keywords: [
      "big",
      "picture",
      "mode",
      "controller",
      "gamepad",
      "couch",
      "tv",
      "fullscreen",
      "big picture mode",
      "console mode",
    ],
    section: "Gaming",
    navigate: navigate => {
      navigate("/settings");
      setTimeout(() => {
        const element = document.getElementById("big-picture-settings");
        if (element) {
          element.scrollIntoView({ behavior: "smooth", block: "center" });
          element.classList.add("highlight-setting");
          setTimeout(() => {
            element.classList.remove("highlight-setting");
          }, 4000);
        }
      }, 100);
    },
  },
  {
    id: "controller-type",
    title: "Controller Type",
    description: "Select your controller type for proper button mapping",
    keywords: [
      "controller",
      "type",
      "gamepad",
      "xbox",
      "playstation",
      "ps4",
      "ps5",
      "generic",
      "button mapping",
      "controller layout",
    ],
    section: "Gaming",
    navigate: navigate => {
      navigate("/settings");
      setTimeout(() => {
        const element = document.getElementById("big-picture-settings");
        if (element) {
          element.scrollIntoView({ behavior: "smooth", block: "center" });
          element.classList.add("highlight-setting");
          setTimeout(() => {
            element.classList.remove("highlight-setting");
          }, 4000);
        }
      }, 100);
    },
  },
  {
    id: "keyboard-layout",
    title: "Keyboard Layout / Big Picture Keyboard",
    description: "Choose keyboard layout for Big Picture virtual keyboard",
    keywords: [
      "keyboard",
      "layout",
      "qwerty",
      "azerty",
      "qwertz",
      "virtual",
      "on-screen",
      "big picture",
      "keyboard type",
    ],
    section: "Gaming",
    navigate: navigate => {
      navigate("/settings");
      setTimeout(() => {
        const element = document.getElementById("big-picture-settings");
        if (element) {
          element.scrollIntoView({ behavior: "smooth", block: "center" });
          element.classList.add("highlight-setting");
          setTimeout(() => {
            element.classList.remove("highlight-setting");
          }, 4000);
        }
      }, 100);
    },
  },
  {
    id: "torbox-api-key",
    title: "TorBox API Key",
    description: "Configure TorBox debrid integration",
    keywords: [
      "torbox",
      "api",
      "key",
      "debrid",
      "integration",
      "configure",
      "setup",
      "token",
    ],
    section: "Downloads",
    scrollTo: "torbox-api-key",
  },
  {
    id: "prioritize-torbox",
    title: "Prioritize TorBox Over Seamless",
    description: "Use TorBox instead of seamless downloads when available",
    keywords: [
      "prioritize",
      "torbox",
      "seamless",
      "prefer",
      "priority",
      "use torbox",
      "torbox first",
    ],
    section: "Downloads",
    scrollTo: "prioritize-torbox",
  },
  {
    id: "single-stream",
    title: "Single Stream Download",
    description: "Use single connection for downloads",
    keywords: [
      "single",
      "stream",
      "download",
      "connection",
      "stable",
      "one",
      "single connection",
      "one stream",
    ],
    section: "Downloads",
    scrollTo: "single-stream",
  },
  {
    id: "download-threads",
    title: "Download Threads",
    description: "Configure number of parallel download connections",
    keywords: [
      "download",
      "threads",
      "connections",
      "parallel",
      "speed",
      "performance",
      "concurrent",
      "multiple connections",
    ],
    section: "Downloads",
    scrollTo: "download-threads",
  },
  {
    id: "analytics",
    title: "Ascendara Analytics / Analytics",
    description: "Help improve Ascendara by sharing anonymous usage data",
    keywords: [
      "ascendara",
      "analytics",
      "telemetry",
      "data",
      "privacy",
      "tracking",
      "usage data",
      "statistics",
    ],
    section: "Advanced",
    scrollTo: "analytics",
  },
  {
    id: "timemachine",
    title: "Ascendara Timemachine / Time Machine",
    description: "Show old download links for games",
    keywords: [
      "ascendara",
      "timemachine",
      "time",
      "machine",
      "old",
      "links",
      "archive",
      "history",
      "previous versions",
      "old versions",
    ],
    section: "Advanced",
    scrollTo: "timemachine",
  },
  {
    id: "workshop-downloader",
    title: "Workshop Downloader / Ascendara Workshop Downloader",
    description: "Download Steam Workshop items",
    keywords: [
      "workshop",
      "downloader",
      "steam",
      "mods",
      "items",
      "steam workshop",
      "download mods",
    ],
    section: "Advanced",
    scrollTo: "workshop-downloader",
  },
  {
    id: "components",
    title: "Components & Dependencies",
    description: "Manage Ascendara components and dependencies",
    keywords: [
      "components",
      "dependencies",
      "sidecar",
      "tools",
      "install",
      "manage",
      "system components",
    ],
    section: "Advanced",
    scrollTo: "components",
  },
  {
    id: "experimental-features",
    title: "Experimental Features",
    description: "Enable experimental and beta features",
    keywords: ["experimental", "beta", "features", "testing"],
    section: "Advanced",
    scrollTo: "experimental-features",
  },
];
