<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>StartupMaster</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ApplicationDefinition Include="StartupMaster\App.xaml" />
    <None Remove="app.ico" />
    <EmbeddedResource Include="app.ico" LogicalName="app.ico" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Management">
      <HintPath>dist\StartupMaster_v1.6\System.Management.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceProcess.ServiceController">
      <HintPath>dist\StartupMaster_v1.6\System.ServiceProcess.ServiceController.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Win32.TaskScheduler">
      <HintPath>dist\StartupMaster_v1.6\Microsoft.Win32.TaskScheduler.dll</HintPath>
    </Reference>
    <Reference Include="ModernWpf">
      <HintPath>dist\StartupMaster_v1.6\ModernWpf.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>