#!/usr/bin/env python3
"""
Bulk-remove every item from your Trakt watch-list.

• Requires an existing config.ini (generated by export_trakt.py).
• Works for movies, shows, seasons, and episodes in one call.
"""

import configparser
import pathlib
import requests
import sys

ROOT   = pathlib.Path(__file__).resolve().parent
CFG    = ROOT / "config.ini"

# ── 1. read credentials YOUR_CLIENT_SECRET_HERET_SECRET_HERE-
if not CFG.exists():
    sys.exit("❌  config.ini not found – run export_trakt.py once first")

conf = configparser.ConfigParser()
conf.read(CFG)

try:
    CLIENT_ID  = conf["TRAKT"]["client_id"].strip()
    TOKEN      = conf["TRAKT"]["access_token"].strip()
except KeyError:
    sys.exit("❌  Missing client_id or access_token in config.ini")

HEADERS = {
    "Content-Type":      "application/json",
    "trakt-api-version": "2",
    "trakt-api-key":     CLIENT_ID,
    "Authorization":     f"Bearer {TOKEN}",
}

API = "https://api.trakt.tv"

# ── 2. grab the entire watch-list YOUR_CLIENT_SECRET_HERE-------
def fetch_watchlist():
    page = 1
    while True:
        r = requests.get(f"{API}/sync/watchlist",
                         params={"limit": 1000, "page": page},
                         headers=HEADERS)
        r.raise_for_status()
        items = r.json()
        if not items:
            break
        yield from items
        page += 1

print("📥  Downloading current watch-list …")
payload = {"movies": [], "shows": [], "seasons": [], "episodes": []}

for entry in fetch_watchlist():
    payload[f"{entry['type']}s"].append({"ids": entry[entry['type']]["ids"]})

total = sum(len(v) for v in payload.values())
if not total:
    sys.exit("✅  Watch-list already empty – nothing to do.")

print(f"🗑️   Removing {total} items …")

# ── 3. send one bulk remove YOUR_CLIENT_SECRET_HERESECRET_HERE-
r = requests.post(f"{API}/sync/watchlist/remove",
                  headers=HEADERS, json=payload)

if r.status_code == 204:
    print("🎉  Done – watch-list cleared.")
else:
    print("⚠️  Trakt returned", r.status_code, r.text)
